Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -52,35 +52,35 @@ commands:
           name: Updating build config with new image details
           command: |
             cd ~/build/$config_path
-            [ -f "./$config_file" ] && echo "Deployment config found" || { echo "Error: deployment config file not found: $config_file." >&2; exit 1; }
+            [ -f "./${config_file}" ] && echo "Deployment config found" || { echo "Error: deployment config file not found: ${config_file}." >&2; exit 1; }
             sed -i "s|image: .*/${image_name}:.*|image: ${container_repo}/${image_name}:${image_tag}|" ${config_file}
-            cat ./$config_File
-            grep -q "$container_repo/$image_name:$image_tag" ./$config_file || { echo "Error: Unable to add new image name to deployment file" >&2; exit 1; }
+            cat ./${config_file}
+            grep -q "${container_repo}/${image_name}:${image_tag}" ./${config_file} || { echo "Error: Unable to add new image name to deployment file" >&2; exit 1; }
       - run:
           name: Fetch previous image label
           command: |
-            export previous_image=$(kubectl get deployment $deployment_name -o=jsonpath='{$.metadata.annotations.previous_image}')
-            echo "previous_image=$previous_image"
+            export previous_image=$(kubectl get deployment ${deployment_name} -o=jsonpath='{$.metadata.annotations.previous_image}')
+            echo "previous_image=${previous_image}"
       - run:
           name: Deploy to GKE
-          command: kubectl apply -f ~/build/$config_path/$config_file
+          command: kubectl apply -f ~/build/${config_path}/${config_file}
       - run:
           name: Fetch new image label
           command: 
-            export current_image=$container_repo/$image_name:$image_tag
-            echo "current_image=$current_image"
+            export current_image=${container_repo}/${image_name}:${image_tag}
+            echo "current_image=${current_image}"
       - run:
           name: Record image version in case of rollback
           command: |
-            kubectl annotate --overwrite deployment $deployment_name \
-            current-image="$current_image" \
-            previous-image="$previous_image" \
+            kubectl annotate --overwrite deployment ${deployment_name} \
+            current-image="${current_image}" \
+            previous-image="${previous_image}" \
             update-time="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
       - run:
           name: Push the new version to git
           command: |
             cd ~/build
-            git add ./$config_path
+            git add ./${config_path}/${config_file}
             git commit -m "Update image tag to new-tag"
             git push origin main
 
